### ISSUE TITLE
Installing custom .unitypackage missing version info

### ISSUE THREAD

**Issue by ericraue** [modesttree/Projeny#12]
I added a ReleaseSource to C:/Users/Eric/Projeny.yaml to the folder E:/UnityPackages, which contains .unitypackage files created from my own projects. They show up in the Releases panel but don't have a version number. When I try to install them I'm given the following error (from PrjLog):
```
Started EditorApi with arguments: E:\ProjenyProjectTest\Experiment\Projeny.yaml TTSDev windows installRelease testing [SharedUnityPackagesDir]
Installing release 'testing' into package dir '[SharedUnityPackagesDir]' with version code 'None'
Attempting to install release with ID 'testing' into package root '[SharedUnityPackagesDir]' and version code 'None'
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Traceback (most recent call last):
  File "C:\Projeny\Source\prj\main\EditorApi.py", line 43, in run
    self._runInternal()
  File "C:\Projeny\Source\prj\main\EditorApi.py", line 105, in _runInternal
    self._releaseSourceManager.installReleaseById(releaseName, self._project, packageRoot, versionCode, True)
  File "C:\Projeny\Source\prj\reg\ReleaseSourceManager.py", line 119, in installReleaseById
    releaseVersionCode = int(releaseVersionCode)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Here's what the PrjLog says about the testing.unitypackage when I click the refresh button. It's missing the Version, VersionCode, and AssetStoreInfo.
```
CompressedSize: 521
FileModificationDate: 2016-02-16 06:55:11.599798
Id: testing
LocalPath: E:/UnityPackages\testing.unitypackage
Name: testing
```

I searched to see how to set the version of a package but came up empty. What am I missing? Thanks!

**Comment by svermeulen** [comment]
You can specify a version using a naming convention on the unitypackage.  For example, for a package named Zenject with version 3.3 you can name the file `Zenject@3.3.unitypackage`

But it SHOULD allow for an empty version, so this is a bug that I'll fix.

Note also that unitypackage files that come from the asset store do not need this naming convention because they have all this metadata compiled into the unitypackage.

**Comment by svermeulen** [comment]
Ok this should be fixed now.  If you're running from source, can you try updating and let me know if this worked?

**Comment by ericraue** [comment]
Ah I missed the @ symbol. The bug fix for empty version works too. Thanks.

**Comment by svermeulen** [comment]
You didn't miss it, I forgot to document that  :)   Fixed now
