### ISSUE TITLE
Can not find Projeny -> Package Manager

### ISSUE THREAD

**Issue by JenkinJoe** [modesttree/Projeny#17]
Hello there,

I very much appreciate the work you did here, but unfortunately its not working for me.

Personal information:

- OS: Windows 10 64bit
- Unity Version: 5.3.4f1
- Visual Studio Version: 2015

I've downloaded the latest binary and after installation I've added my [Install Directory]/Bin directory to system Path. 
Then I started an entirely new set of Projeny-based packages/projects from scratch (prj -cc) and additionaly initialized it in the root directory (prj --init). 
I've also set the VisualStudioIdePath value in my Projeny.yaml as well as the Projeny-generated visual studio solution as my primary editor.

I can't see the menu item Projeny, which is why I wasn't able to create a new project nor was I able to manage an existing one.

What is the solution for this? - A reinstallation didn't help.

[PrjLog.txt](https://github.com/modesttree/Projeny/files/200103/PrjLog.txt)

**Comment by svermeulen** [comment]
What directory are you opening in Unity?

If you want to make sure you're opening the right directory, try going to an empty directory and doing this:

    prj -cc
    prj -p TestProject -cpr -ou

I actually have the exact same info as you (OS / unity version / vs version) and this worked for me using release 0.3.3

**Comment by svermeulen** [comment]
My best guess is that you're opening `C:\Users\Bres\Documents\Unity\UnityProjects\Colonizer` instead of `C:\Users\Bres\Documents\Unity\UnityProjects\Colonizer\Colonizer-Windows`

**Comment by JenkinJoe** [comment]
Thanks that helped me.
