### ISSUE TITLE
Projeny deletes references when it generates the VS project

### ISSUE THREAD

**Issue by MegaThorx** [modesttree/Projeny#19]
I got 3 packages in projeny (Client, Server, Shared). Now i need to create everytime the references in Client for Shared and with the package Server the same. 

It's just a little bit annoying.

Keep up the good work :+1:

**Comment by svermeulen** [comment]
Did you declare the dependencies between those projects in a `ProjenyPackage.yaml` file?

If you do that, the C# projects will automatically be generated with those dependencies.  It will also allow projeny to be more intelligent when adding those projects to your unity project, or when moving those packages between the assets folder and plugins folder.

**Comment by svermeulen** [comment]
The C# projects in the projeny-generated solution are 100% generated, so any changes you make to them will be clobbered the next time you get projeny to update

**Comment by MegaThorx** [comment]
Thanks
