### ISSUE TITLE
Utf-8 issue with demo project with non english languages

### ISSUE THREAD

**Issue by malvakian** [modesttree/Projeny#22]
All files used are from release [Version 0.3.4](https://github.com/modesttree/projeny/releases).

Following instructions in readme i can't init demo project. See [PrjLog.txt](https://github.com/modesttree/Projeny/files/247198/PrjLog.txt)
Looking in solved problems I found issue [#14](https://github.com/modesttree/Projeny/issues/14), in a comment is requested change language to English of the operating system to solve a similar problem. And it have worked for me too.

My main language is Spanish, following your instrucions i have executed mklink command and I recieved this "mklink /J "E:\Projeny-tests\UnityProjects\jor" "E:\Projeny-tests\UnityProjects\SphereMover\ProjectSettings"
**Unión** creada para E:\Projeny-tests\UnityProjects\jor <<===>> E:\Projeny-tests\UnityProjects\SphereMover\ProjectSettings"

I thought that issue had already been fixed in the latest release, someone can help me?

Thanks in advance.

**Comment by svermeulen** [comment]
Hmm that's odd.  I just tried to reproduce the issue using Version 0.3.4 and with Spanish language enabled and it worked fine.  I also confirmed that executing "mklink /J x y" prints out "Unión creada para y <<===>> x" just like in your case.

Can you try running from source?  Would be helpful to see a call stack of where his is happening

**Comment by svermeulen** [comment]
Or alternatively, can you try installing this and trying it again?  It has a change I'm guessing might help

[ProjenyInstaller-v0.3.4.zip](https://github.com/modesttree/Projeny/files/247717/ProjenyInstaller-v0.3.4.zip)

**Comment by malvakian** [comment]
Hi svermeulen, 

Is all my fault, I had an previous version of projeny and a windows path linked to that old version.

I'm really sorry I wasted your time.

Best regards.

**Comment by svermeulen** [comment]
Ok glad to hear you got it sorted
