### ISSUE TITLE
Validation failed due to presence of generated .vs folder

### ISSUE THREAD

**Issue by drhaynes** [modesttree/Projeny#27]
Using Visual Studio 2015 on Windows 10. Getting the following error:

![image](https://cloud.githubusercontent.com/assets/117291/15604017/dd90c1f6-23f5-11e6-8c45-b46b8c7cdf93.png)

**Comment by svermeulen** [comment]
I can't reproduce this one.  For me, the `.vs` directory is always created in the same directory as the VS solution (eg. `UnityProjects/MyProject/.vs`) so this isn't a problem.  How did you get it to create it in plugins?

**Comment by drhaynes** [comment]
Not sure how the .vs folder got there. Just from normal Unity/VS usage.

This seems to be fixed in the latest version.
