### ISSUE TITLE
What about the StreamingAssets folder?

### ISSUE THREAD

**Issue by cutepig49** [modesttree/Projeny#29]
It seems that the folder must be placed in /Assets.

Do I have to create A pakcage named StreamingAssets?

**Comment by svermeulen** [comment]
For all of Unity's [special folder types](http://docs.unity3d.com/Manual/SpecialFolders.html) that are not recursive (ie. Gizmos, EditorDefaultResources, WebPlayerTemplates, etc.), you need to create a separate package for it then mark that package with that FolderType.  Note that Resources and Editor folders can be placed anywhere so don't apply to this.

Search for 'FolderType' in the docs page to see what I mean

**Comment by cutepig49** [comment]
But after I added a package which with "FolderType: StreamingAssets" to my project, the projeny said "Projeny validation failed".

**Comment by svermeulen** [comment]
Oh you're right this is a bug.  I fixed this in source and will be making a release soon.  I also changed the really obnoxious popup into a log statement
