### ISSUE TITLE
Unable to add AssetStore packages.

### ISSUE THREAD

**Issue by MartinLange** [modesttree/Projeny#40]
Whenever i try to add an UnityPackage downloaded from the store I get this error : 

> PrjCommandException: Error occurred during 'Installing release 'DOTween (HOTween v2)'': [WinError 2] The system cannot find the file specified

I can see it's because it tries to call "C:/Program Files/Unity/Editor/Unity.exe"
But i use "C:/Program Files/Unity5.3/Editor/Unity.exe" as path

**Comment by svermeulen** [comment]
Was there a reason you closed this?

You can customize your Unity path by setting the `UnityExePath` variable in your `Projeny.yaml` config file.  You can also add this as a machine specific setting by adding a file at `C:/Users/YourUserName/Projeny.yaml`

**Comment by MartinLange** [comment]
Yeah i sorry forgot to write the reason. I found the way to specify the path, so I closed it. Thanks for Replying. Great tool by the way
