### ISSUE TITLE
Import packages into the Resources folder

### ISSUE THREAD

**Issue by markffrench** [modesttree/Projeny#44]
Hi,

As far as I can tell, the current setup only allows you to have one Resources package in your packages directory.

It would be handy if I could compose our Resources folder out of multiple, platform-dependent packages.

p.s. great package btw!

**Comment by svermeulen** [comment]
You should be able to have as many Resources folders as you want in your project.  Though with Projeny, of course, they all have to be inside packages. You can have a Resources folder in the root of your package directory or in any sub directory, it doesn't matter.   Is that not working for you?  I'm not sure what you are suggesting exactly as an alternative to that

**Comment by markffrench** [comment]
Wow, you're absolutely right. I had no idea you could have multiple Resources folders in the same project. Thanks for your help.
