### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by yunspace** [modesttree/Projeny#45]
I'm currently getting the following issue when trying to install asset store dependencies. 

I'm using the standard sample project, however my setup is slightly different in that:

- Unity editor, Projeny and the sample projects are all in D:\ drive. 
- Asset Store packages are in the default C:\ drive location

Not sure if this error rings a bell at all. I will try and move everything into the same drive and see if I still get the error.

```
PrjCommandException: Error occurred during 'Installing release 'Zenject Dependency Injection IOC'': [WinError 2] The system cannot find the file specified

Projeny.Internal.PrjCommandHandler+<ProcessPrjCommand>d__3.MoveNext ()
Projeny.Internal.CoRoutine.Pump ()
Rethrow as CoRoutineException: Coroutine Object Trace: PmDragDropHandler -> PrjCommandHandler
Projeny.Internal.CoRoutine.Pump ()
Projeny.Internal.AsyncProcessor.AdvanceFrameAll ()
Rethrow as AsyncOperationException: Error occurred during async operation
Projeny.Internal.AsyncProcessor.AdvanceFrameAll ()
Projeny.Internal.AsyncProcessor.Tick ()
Projeny.Internal.PmCompositionRoot.Update ()
Projeny.Internal.PmWindow.Update ()
UnityEngine.Debug:LogException(Exception)
Projeny.Internal.Log:ErrorException(Exception)
Projeny.Internal.PmWindow:OnErrorOccurred(Exception)
Projeny.Internal.PmWindow:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

**Comment by svermeulen** [comment]
What version of unity are you using?

**Comment by yunspace** [comment]
Oh it's 5.5.0b11...

**Comment by svermeulen** [comment]
Sorry I haven't been able to take a look at this.  I'm tied up for the next few weeks, but will take a look then.

**Comment by yunspace** [comment]
I use Unity stable version 5.4.3f1 and tried to the following:

- Unity installed on D: drive + Project on D: drive, get same error
- Unity installed on D: drive + Project on C: drive, get same error
- Unity on C: drive + Project on C: drive, everything works.
- Unity on C: drive + Project on D: drive, everything works

I think the Unity editor must be installed in the same drive as the Asset Store download folder. Which defaults to `C:\Users\accountName\AppData\Roaming\Unity\Asset Store`

This probably isn't really a bug but worth mentioning in the README installation instructions perhaps?

**Comment by yunspace** [comment]
Closing for now. Will raise a PR with README update later.
