### ISSUE TITLE
Error when trying to update solution: VS 2015 and Unity 5.4.2

### ISSUE THREAD

**Issue by brunoleos** [modesttree/Projeny#47]
I get the following error when an update is needed (via buttons in the Package Manager):

> PrjCommandException: Error occurred during 'Updating solution': Error: Could not find unity-generated project when generating custom solution.  This is necessary so the custom solution can add things like unity defines and DLL references within the unity project.

> Projeny.Internal.PrjCommandHandler+<ProcessPrjCommand>d__3.MoveNext ()
Projeny.Internal.CoRoutine.Pump ()
Rethrow as CoRoutineException: Coroutine Object Trace: PmVsSolutionViewHandler -> PrjCommandHandler
Projeny.Internal.CoRoutine.Pump ()
Projeny.Internal.AsyncProcessor.AdvanceFrameAll ()
Rethrow as AsyncOperationException: Error occurred during async operation
Projeny.Internal.AsyncProcessor.AdvanceFrameAll ()
Projeny.Internal.AsyncProcessor.Tick ()
Projeny.Internal.PmCompositionRoot.Update ()
Projeny.Internal.PmWindow.Update ()
UnityEngine.Debug:LogException(Exception)
Projeny.Internal.Log:ErrorException(Exception)
Projeny.Internal.PmWindow:OnErrorOccurred(Exception)
Projeny.Internal.PmWindow:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by svermeulen** [comment]
Can you tell me the name of the unity generated solution?  I wonder if unity is naming it something unexpected.

Here's what mine is:

![image](https://cloud.githubusercontent.com/assets/810762/21957304/f8414022-da69-11e6-9901-85295e734227.png)

**Comment by brunoleos** [comment]
Indeed the name of my CS project follow a different pattern:

![projeny-solution](https://cloud.githubusercontent.com/assets/16419952/22019528/16139efa-dc9b-11e6-8434-b74ace93f455.png)
Do you know a workaround?

**Comment by svermeulen** [comment]
I don't know why Unity generates these visual studio files completely differently depending on the machine.  But I've changed it to handle this new variation.  Can you try the attached build?  Or updating from source if you're directly using source.

[ProjenyInstaller-v0.3.5.zip](https://github.com/modesttree/Projeny/files/712492/ProjenyInstaller-v0.3.5.zip)

**Comment by brunoleos** [comment]
The fix works ;)

**Comment by svermeulen** [comment]
I figured out what was causing the different styles of naming.  It has to do with the external editor preference that you have set up for your unity.  If you have it set to monodevelop or a custom editor then `Assembly-CSharp` is used, or if you use visual studio, this other variation is used
