### ISSUE TITLE
Projeny support windows environment?

### ISSUE THREAD

**Issue by daroubing** [modesttree/Projeny#52]
Can I can edit ProjenyProject.yaml  -'[Some Environment Var]/PathToUnityProject' ?

**Comment by svermeulen** [comment]
It doesn't currently allow substituting environment variables but this could be added pretty easily

**Comment by daroubing** [comment]
Multi developer has different path with UnityEditor or Project.It is a useful feature. Then all developer can re-use one ProjenyProject.yaml.
Can add this feature in next version? Thanks.

**Comment by svermeulen** [comment]
If you have a different path for the unity editor, you can set that up per-machine by adding a `Projeny.yaml` file in your windows user home directory with contents for example

    PathVars:
        UnityExePath: 'C:/Utils/Unity/Editor/Unity.exe'

I'm not sure what the other case is you're talking about.  What do you mean developers might have different projects?

**Comment by svermeulen** [comment]
Oh, are you saying different projects might use different versions of unity?

**Comment by daroubing** [comment]
we team has many developers. some developer install unity editor in "c:/Unity/Editor/Unity.exe",and two unity project in "d:/Project/UnityProject1"and "d:/Project/UnityProject2".
    other develper has different path, Unity Editor in "d:/ProTools/Editor/Unity.exe" and project in "E:/WorkProject/UntiyProject1"and "E:/WorkProject/TestUnityProject2".
    UnityProject1 and UnityProject2 in git version control,and  UnityProject2 use Projeny depend on UnityProject1. Every developer must edit self UnityProject2's Projeny.yaml and ProjenyProject.yaml,,and this file different git server file.

**Comment by svermeulen** [comment]
I'm not sure why environment variables solve your problem, but like I said it's trivial to add, so I've done this for you with the latest commit.  I haven't created a release yet but if you want to try it you can run from source

**Comment by daroubing** [comment]
Thanks.

- I'm set environment WORK_DIR And UNITY_EDITOR_DAYDREAM.
- Set Projeny.yaml
![image](https://cloud.githubusercontent.com/assets/22874210/22171719/53e9ccea-dfcf-11e6-9b28-ff945e76c3e1.png)
Set ProjenyProject.yaml
![image](https://cloud.githubusercontent.com/assets/22874210/22171727/7f9f1200-dfcf-11e6-88dc-20775f2437f1.png)
get a error
![image](https://cloud.githubusercontent.com/assets/22874210/22171729/92f32742-dfcf-11e6-989e-af443b59ac8d.png)
and Log
![image](https://cloud.githubusercontent.com/assets/22874210/22171734/ac2f2f76-dfcf-11e6-8191-08f815291323.png)

**Comment by svermeulen** [comment]
This is because WorkDir is not a string.  You need to change WorkDir and UnityEditor to something like this:

```
PathVars:
    WorkDir: '[WORK_DIR]'
    UnityEditor: '[UNITY_EDITOR_DAYDREAM]'
```

For more details on YAML parsing see [here](https://en.wikipedia.org/wiki/YAML)

**Comment by daroubing** [comment]
You are right. 
I use WorkDir: '[WORK_DIR]'.but error 
![image](https://cloud.githubusercontent.com/assets/22874210/22173281/c320e656-dff8-11e6-8677-0213ec31e31f.png)
I replace new dll Projeny.dll and YamlDotNet.dll in "Projeny\Editor".Is right?

**Comment by svermeulen** [comment]
Can you attach your PrjLog.txt?

**Comment by daroubing** [comment]
I open projeny->pakcage manager.
[PrjLog.txt](https://github.com/modesttree/Projeny/files/721664/PrjLog.txt)
