### ISSUE TITLE
Why no .exe builds?

### ISSUE THREAD

**Issue by brewmanandi** [modesttree/Projeny#76]
I am now stuck on the last .exe build because clearly I cannot force everybody on the team to have python set up. Give me at least a run through how to do my own exe builds?

**Comment by svermeulen** [comment]
I didn't know anyone cared about the exe builds anymore, but now that I do I'll take a look at resurrecting them this weekend

**Comment by svermeulen** [comment]
Ok exe builds should be back now as of version 0.3.10.  Let me know if you run into any issues with it, in my basic tests it worked fine.

**Comment by brewmanandi** [comment]
Awesome!
