### ISSUE TITLE
Failed During Task: Updating Package Directories

### ISSUE THREAD

**Issue by RTE1818** [modesttree/Projeny#89]
I am getting the following command line output:

Initializing new project-platform "Toybox-Windows"...
   Updating package directories for project Toybox...
      Project "Toybox" is not initialized for platform "Windows".  Initializing now.
      Initializing new project Toybox (Windows)...
         Finished creating new project "Toybox" (Windows)
      Finished initializing new project Toybox (Windows) (Took 1.9 seconds, time: 15:02:43, total elapsed: 1.9
 seconds)
   Failed during task:  updating package directories for project Toybox (Took 2.9 seconds, time: 15:02:44, tot
al elapsed: 3.0 seconds)
Failed during task:  initializing new project-platform "Toybox-Windows" (Took 2.9 seconds, time: 15:02:44, tot
al elapsed: 3.0 seconds)
Error!
See PrjLog.txt for more details
Operation completed with errors.  Took 3.0 seconds.

[PrjLog.txt](https://github.com/modesttree/Projeny/files/2621502/PrjLog.txt)

**Comment by RTE1818** [comment]
This is the contents of the ProjenyProject.yaml's I am using in the UnityPackages folder vs the one that is generating within the project (both converted to a txt file). 

[ProjenyProject (At UnityProjects Folder).txt](https://github.com/modesttree/Projeny/files/2622367/ProjenyProject.At.UnityProjects.Folder.txt)

[ProjenyProject (Generated with new Project).txt](https://github.com/modesttree/Projeny/files/2622368/ProjenyProject.Generated.with.new.Project.txt)

**Comment by svermeulen** [comment]
The error message suggests it's hitting this assert inside `UnityEditorMenuGenerator.py`:
```csharp
assertThat(not foundCurrent)
```
Which suggests that it's somehow finding multiple instances of the same project and platform pair.  I can't think of what would be causing that though.  This is just the code that generates the unity menu to change between projects though, so not critical.  Can you try just removing that assert?

**Comment by RTE1818** [comment]
Just to be sure, I've deleted that project and all links and created a new project under a different name. Here's the PrjLog this time.

[PrjLog.txt](https://github.com/modesttree/Projeny/files/2624909/PrjLog.txt)

**Comment by svermeulen** [comment]
Are you able to run projeny directly from source?   You'll need to do it that way so you can remove that assert line
